included:
  - HFPPlayer

excluded:
  - HFPPlayer.xcodeproj
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - first_where
  - force_unwrapping

line_length:
  warning: 120
  error: 160

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 250
  error: 350

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  excluded:
    - id
    - vm
    - hfp
    - url
